POST http://localhost:8080/api/syousai HTTP/1.1
Content-Type: application/json

{
 /////////詳細検索用/////////
 //"areas_id": 1,
 //"season":"秋",
 //"startDate":"2023-07-24"
 //"genre": "見る"
 ///////////////////////////

 
 /////////キーワード検索用/////////
 //"keyword" : ""
 /////////////////////////////////
}
//適当に変えると検索結果かわるはずです
//キーワード検索はsearchに変えてテストしてください
//ジャンルを指定するとその他の条件を指定しても
//指定したジャンルのイベントが全て表示されてしまいます・・・

