PUT http://localhost:8080/api/review/1 HTTP/1.1
Content-Type: application/json

{
    "satisfaction": 5,
    "security": 4,
    "again": 3,
    "atmosphere": 4,
    "continuation": 5,
    "revTitle": "Updated Review",
    "comment": "This is an updated review.",
    "revImage": "image_url"
}
