POST http://localhost:8080/api/review/post HTTP/1.1
content-type: application/json

{
    "satisfaction": 0,
    "security": 0,
    "again": 0,
    "atmosphere": 0,
    "continuation": 0,
    "revTitle": "テスト",
    "comment": "コメントテスト",
    "revImage": "画像テスト",
    "event": {
        "id": 1
}
}